// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accrual.sql

package database

import (
	"context"

	"github.com/shopspring/decimal"
)

const getOrdersForProcessing = `-- name: GetOrdersForProcessing :many
select number, user_id, status, accrual, uploaded_at
from orders
where status in ('NEW','PROCESSING')
order by uploaded_at asc
`

func (q *Queries) GetOrdersForProcessing(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersForProcessing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Number,
			&i.UserID,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
update orders
set status = $2,
    accrual = $3
where number = $1
`

type UpdateOrderStatusParams struct {
	Number  string
	Status  string
	Accrual decimal.Decimal
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Number, arg.Status, arg.Accrual)
	return err
}
