// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Order struct {
	Number     string
	UserID     uuid.UUID
	Status     string
	Accrual    decimal.Decimal
	UploadedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	CreatedAt    time.Time
}

type Withdrawal struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	OrderNumber string
	Sum         decimal.Decimal
	ProcessedAt time.Time
}
