// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOrderOwner = `-- name: GetOrderOwner :one
select user_id
from orders
where number = $1
`

func (q *Queries) GetOrderOwner(ctx context.Context, number string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrderOwner, number)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertOrder = `-- name: InsertOrder :one
insert into orders (number, user_id)
values ($1, $2)
on conflict(number) do nothing
returning user_id
`

type InsertOrderParams struct {
	Number string
	UserID uuid.UUID
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.Number, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
