// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :one
insert into users (id, login, password_hash)
values ($1, $2, $3)
returning id
`

type InsertUserParams struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Login, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const selectUserByLogin = `-- name: SelectUserByLogin :one
select id, login, password_hash, created_at
from users
where login = $1
`

func (q *Queries) SelectUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
