// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package handler

import (
	"errors"
	"fmt"
)

const (
	// HealthStatusOk is a HealthStatus of type Ok.
	HealthStatusOk HealthStatus = iota
)

var ErrInvalidHealthStatus = errors.New("not a valid HealthStatus")

const _HealthStatusName = "ok"

var _HealthStatusMap = map[HealthStatus]string{
	HealthStatusOk: _HealthStatusName[0:2],
}

// String implements the Stringer interface.
func (x HealthStatus) String() string {
	if str, ok := _HealthStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("HealthStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HealthStatus) IsValid() bool {
	_, ok := _HealthStatusMap[x]
	return ok
}

var _HealthStatusValue = map[string]HealthStatus{
	_HealthStatusName[0:2]: HealthStatusOk,
}

// ParseHealthStatus attempts to convert a string to a HealthStatus.
func ParseHealthStatus(name string) (HealthStatus, error) {
	if x, ok := _HealthStatusValue[name]; ok {
		return x, nil
	}
	return HealthStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidHealthStatus)
}

// MarshalText implements the text marshaller method.
func (x HealthStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *HealthStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseHealthStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *HealthStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
