// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package repository

import (
	"errors"
	"fmt"
)

const (
	// MigrationActionUp is a MigrationAction of type Up.
	MigrationActionUp MigrationAction = iota
	// MigrationActionDrop is a MigrationAction of type Drop.
	MigrationActionDrop
)

var ErrInvalidMigrationAction = errors.New("not a valid MigrationAction")

const _MigrationActionName = "updrop"

var _MigrationActionMap = map[MigrationAction]string{
	MigrationActionUp:   _MigrationActionName[0:2],
	MigrationActionDrop: _MigrationActionName[2:6],
}

// String implements the Stringer interface.
func (x MigrationAction) String() string {
	if str, ok := _MigrationActionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MigrationAction(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MigrationAction) IsValid() bool {
	_, ok := _MigrationActionMap[x]
	return ok
}

var _MigrationActionValue = map[string]MigrationAction{
	_MigrationActionName[0:2]: MigrationActionUp,
	_MigrationActionName[2:6]: MigrationActionDrop,
}

// ParseMigrationAction attempts to convert a string to a MigrationAction.
func ParseMigrationAction(name string) (MigrationAction, error) {
	if x, ok := _MigrationActionValue[name]; ok {
		return x, nil
	}
	return MigrationAction(0), fmt.Errorf("%s is %w", name, ErrInvalidMigrationAction)
}

// MarshalText implements the text marshaller method.
func (x MigrationAction) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MigrationAction) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMigrationAction(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *MigrationAction) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
