// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// OrderStatusNEW is a OrderStatus of type NEW.
	OrderStatusNEW OrderStatus = iota
	// OrderStatusPROCESSING is a OrderStatus of type PROCESSING.
	OrderStatusPROCESSING
	// OrderStatusINVALID is a OrderStatus of type INVALID.
	OrderStatusINVALID
	// OrderStatusPROCESSED is a OrderStatus of type PROCESSED.
	OrderStatusPROCESSED
)

var ErrInvalidOrderStatus = errors.New("not a valid OrderStatus")

const _OrderStatusName = "NEWPROCESSINGINVALIDPROCESSED"

var _OrderStatusMap = map[OrderStatus]string{
	OrderStatusNEW:        _OrderStatusName[0:3],
	OrderStatusPROCESSING: _OrderStatusName[3:13],
	OrderStatusINVALID:    _OrderStatusName[13:20],
	OrderStatusPROCESSED:  _OrderStatusName[20:29],
}

// String implements the Stringer interface.
func (x OrderStatus) String() string {
	if str, ok := _OrderStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("OrderStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OrderStatus) IsValid() bool {
	_, ok := _OrderStatusMap[x]
	return ok
}

var _OrderStatusValue = map[string]OrderStatus{
	_OrderStatusName[0:3]:   OrderStatusNEW,
	_OrderStatusName[3:13]:  OrderStatusPROCESSING,
	_OrderStatusName[13:20]: OrderStatusINVALID,
	_OrderStatusName[20:29]: OrderStatusPROCESSED,
}

// ParseOrderStatus attempts to convert a string to a OrderStatus.
func ParseOrderStatus(name string) (OrderStatus, error) {
	if x, ok := _OrderStatusValue[name]; ok {
		return x, nil
	}
	return OrderStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidOrderStatus)
}

// MarshalText implements the text marshaller method.
func (x OrderStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OrderStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOrderStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OrderStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
